import "./globals.css";
import Navigation from "@/components/Navigation";
import { Metadata } from "next";

// metadata 는 seraver component 에서만, page 에서만, layout 에서만 사용가능
// %s : 다른곳의 title 을 가져와서 병합
export const metadata: Metadata = {
  title: {
    template: "%s | Next Movies",
    default: "Next Movies ",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
